### ISSUE TITLE
게시판 댓글 등록(DB에 댓글 하나도 없을 때)

### ISSUE THREAD

**Issue by ino5** [ino5/spring-web-project-groupware-teamworks#6]
91d74e76166d1351366e4d4d8474328666b0793c

DB에 댓글 하나도 없을 때 댓글 등록 시 500에러 발생

selectOneMaxRp_num의 null exception 에러. NVL함수 사용하면 해결될 것 같습니다.

**Comment by Dasol23** [comment]
a80e5403874741745bcb4b8dc87088b8e2a8c3bc
해결
